# Deploy the platform apps
resources:
- ../../base/am-cdk
- ../../base/idm-cdk
- ../../base/end-user-ui
- ../../base/login-ui
- ../../base/admin-ui

# Set the image to the dev images that are built every night
images:
- name: am
  newName: docker.io/allinformatix/allinformatix-gidp-am
  newTag: 7.5.1
- name: idm
  newName: docker.io/allinformatix/allinformatix-gidp-idm
  newTag: 7.5.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: forgerock
