apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
data:
  # Some optional settings
  # If you are using cert-manager and Let's Encrypt in your cluster and want real certs - set this
  CERT_ISSUER: letsencrypt-dns
  FQDN: "gidp.k8s.prd.allinformatix.com"