
resources:
- restored-data-pvc.yaml
- ds-restore-job.yaml
- ../backup-base


generatorOptions:
  disableNameSuffixHash: true

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app: ds-restore
patches:
- path: gsutil.yaml
