apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ig
spec:
  rules:
    - host: api.dev.allinformatix.com
  tls:
    - hosts:
        - api.dev.allinformatix.com
      secretName: api-sslcert