apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


# kustomize can't patchesStrategicMerge CRD's out of the box - this is the easiest way
resources:
- ../../../base/secrets
patches:
- path: secrets-patch.yaml
  target:
    group: secret-agent.secrets.forgerock.io
    kind: SecretAgentConfiguration
    name: forgerock-sac
    version: v1alpha1
