apiVersion: batch/v1
kind: Job
metadata:
  name: ldif-importer
spec:
  template:
    metadata:
      labels:
        app: ldif-importer
    spec:
      restartPolicy: Never
      containers:
      - name: ldif-importer
        imagePullPolicy: Always
        image: ldif-importer
        envFrom:        
        - secretRef:
            name: ds-env-secrets
        - secretRef:
            name: idm-env-secrets
        - secretRef:
            name: ai-exec-layer-env-secrets     
        - configMapRef:
            name: platform-config
        volumeMounts:
        - mountPath: /var/run/secrets/opendj-passwords
          name: passwords
      securityContext:
        fsGroup: 0
        runAsUser: 11111
      volumes:
      - name: passwords
        secret:
          secretName: ds-passwords
      tolerations:
        - key: kubernetes.io/arch
          operator: Exists
          effect: NoSchedule
