apiVersion: apps/v1
kind: Deployment
metadata:
  name: idm
  labels:
    app: idm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: idm
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
    spec:
      # nodeSelector:
      #   kubernetes.io/arch: amd64
      securityContext:
        runAsUser: 11111
        runAsGroup: 0
      initContainers:
      - name: fbc-init
        image: idm
        imagePullPolicy: Always
        env:
        - name: FQDN
          valueFrom:
            configMapKeyRef:
              name: platform-config
              key: FQDN
        volumeMounts:
        - mountPath: /fbc
          name: fbc
        command:
        - /bin/bash
        - -c
        - |
          if [ -d /fbc/conf ];
          then
            echo "Existing openidm configuration found. Skipping copy"
          else
            echo "Copying docker image configuration files to the shared volume"           
            cd /opt/openidm
            cp -vr ui conf script /fbc
            touch /fbc/conf/ui-configuration.json
            cat <<EOF > /fbc/conf/ui-configuration.json
            {
              "configuration" : {
                "selfRegistration" : false,
                "passwordReset" : false,
                "forgotUsername" : false,
                "lang" : "en",
                "passwordResetLink" : "",
                "platformSettings" : {
                  "adminOauthClient" : "idm-admin-ui",
                  "adminOauthClientScopes" : "fr:idm:*",
                  "amUrl" : "https://${FQDN}/am",
                  "loginUrl" : ""
                },
                "roles" : {
                  "internal/role/openidm-authorized" : "ui-user",
                  "internal/role/openidm-admin" : "ui-admin"
                },
                "notificationTypes" : {
                  "info" : {
                    "name" : "common.notification.types.info",
                    "iconPath" : "images/notifications/info.png"
                  },
                  "warning" : {
                    "name" : "common.notification.types.warning",
                    "iconPath" : "images/notifications/warning.png"
                  },
                  "error" : {
                    "name" : "common.notification.types.error",
                    "iconPath" : "images/notifications/error.png"
                  }
                },
                "defaultNotificationType" : "info"
              }
            }
          EOF
          fi
      - name: truststore-init
        image: idm
        imagePullPolicy: Always
        volumeMounts:
        - name: new-truststore
          mountPath: /truststore
        - name: truststore
          mountPath: /var/run/secrets/truststore
        command: ["/opt/openidm/bin/import-pem-certs.sh"]
        env:
        - name: TRUSTSTORE_PATH
          value: /truststore/idmtruststore
        - name: TRUSTSTORE_PASSWORD
          value: changeit
        # secret agent generated truststore.
        - name: IDM_PEM_TRUSTSTORE
          value: "/var/run/secrets/truststore/cacerts"
        # cert-manager truststore used for the connection to DS
        - name: IDM_PEM_TRUSTSTORE_DS
          value: "/var/run/secrets/truststore/ca.crt"
      containers:
      - name: openidm
        image: idm
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPENIDM_REPO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ds-passwords
              key: dirmanager.pw
        - name: USERSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ds-passwords
              key: dirmanager.pw
        - name: POSTGRES_HOSTNAME
          value: postgres
        - name: POSTGRES_PORT
          value: "5432"
        - name: OPENIDM_DS_IDREPO_USERNAME
          valueFrom:
            secretKeyRef:
              name: idm-env-secrets
              key: OPENIDM_DS_IDREPO_USERNAME
        - name: OPENIDM_DS_IDREPO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: idm-env-secrets
              key: OPENIDM_DS_IDREPO_PASSWORD
        - name: IDM_DB_CONNECTOR_USER
          value: "idm_connector_user"
        - name: IDM_DB_CONNECTOR_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-env-secrets
              key: IDM_DB_CONNECTOR_USER_PASSWORD
        - name: RS_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: amster-env-secrets
              key: IDM_RS_CLIENT_SECRET
        - name: REALMS_ROOT_OAUTH2CLIENTS_ALLINFORMATIX_GLOBALIDP
          valueFrom:
            secretKeyRef:
              name: ig-env-secrets
              key: REALMS_ROOT_OAUTH2CLIENTS_ALLINFORMATIX_GLOBALIDP
        envFrom:
        - configMapRef:
            name: idm
        - configMapRef:
            name: platform-config
        - secretRef:
            name: idm-env-secrets
        livenessProbe:
          httpGet:
            httpHeaders:
            - name: X-OpenIDM-Username
              value: anonymous
            - name: X-OpenIDM-Password
              value: anonymous
            - name: X-OpenIDM-NoSession
              value: "true"
            path: /openidm/info/ping
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 60
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            httpHeaders:
            - name: X-OpenIDM-Username
              value: anonymous
            - name: X-OpenIDM-Password
              value: anonymous
            - name: X-OpenIDM-NoSession
              value: "true"
            path: /openidm/info/ping
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 8080
        - containerPort: 8443
        resources:
          limits:
            memory: 1024Mi
          requests:
            cpu: 250m
            memory: 1024Mi
        volumeMounts:
        - mountPath: /var/run/secrets/idm
          name: idm-secrets
        - name: new-truststore
          mountPath: /opt/openidm/idmtruststore
          readOnly: true
          subPath: idmtruststore
        - mountPath: /opt/openidm/logs
          name: logs
        - mountPath: /opt/openidm/audit
          name: audit-logs
        - mountPath: /var/run/openidm/logging
          name: idm-logging-properties
        - name: fbc
          mountPath: /opt/openidm/conf
          subPath: conf
        - name: fbc
          mountPath: /opt/openidm/ui
          subPath: ui
        - name: fbc
          mountPath: /opt/openidm/script
          subPath: script
      terminationGracePeriodSeconds: 10
      volumes:
      - name: fbc
        emptyDir: {}
      - name: idm-secrets
        secret:
          secretName: idm
      - name: new-truststore
        emptyDir: {}
      - name: truststore
        projected:
          sources:
          - secret:
              name: truststore-pem
          - secret:
              name: ds-ssl-keypair
      - name: logs
        emptyDir: {}
      - name: audit-logs
        emptyDir: {}
      - name: idm-logging-properties
        configMap:
           name: idm-logging-properties
      tolerations:
        - key: kubernetes.io/arch
          operator: Exists
          effect: NoSchedule

