# You either run this as a one shot job:
resources:
- ds-backup-job.yaml
- ../backup-base
- pvc.yaml


# Choose one of the strategies below to backup the files. E.g. to gcs, s3, etc.
# Add your own container here that backs up to the system of choice
# Patch with the gsutil job
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app: ds-backup
patches:
- path: gsutil.yaml
