apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# defines config map patches to set Portal FQDN for STAGE
patches:
- target:
    kind: ConfigMap
    name: platform-config
  patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: platform-config
    data:
      PORTAL_FQDN: "portal.stg.allinformatix.com"
