kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- job.yaml
labels:
- includeSelectors: true
  pairs:
    app: ds-backup-management
    app.kubernetes.io/component: directory
    app.kubernetes.io/instance: ds-backup-management
    app.kubernetes.io/name: ds-backup-management
    app.kubernetes.io/part-of: forgerock
